version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # 필요 시 포트 매핑
    volumes:
      - .:/app # 소스 코드 마운트 (개발 중에만 사용)
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
